# Generated by Django 5.2.3 on 2025-06-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('sensitive_attributes', models.JSONField()),
                ('metrics', models.JSONField()),
                ('suggestions', models.JSONField()),
                ('graph_urls', models.JSONField()),
            ],
        ),
    ]
