# Generated by Django 4.1.13 on 2025-07-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairness', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
