# Generated by Django 4.1.13 on 2025-07-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fairness', '0002_delete_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('mongo_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='processing', max_length=20)),
            ],
        ),
    ]
